### PR TITLE
Replace checkout with restore

### PR DESCRIPTION
**Pull request by RocketPuppy**

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
Does this change require a specific minimum version of git?  If so, we should probably note that in the readme and the first few labs where we help the user setup/install git

**Comment by RocketPuppy** [comment]
Looks like 2.25, from 2020. I can add it if that's new enough for your thresholds. @cpjolicoeur

**Comment by cpjolicoeur** [comment]
nope, I think 2020 is old enough for our needs we dont need to probably change anything

**Review by joealba — APPROVED** [review]

**Comment by RocketPuppy** [comment]
Rebased, peview up here: https://git.withmojo.com/dw/checkout-restore/lab_01.html. @cpjolicoeur I did check the zip and that's working now.

**Review by cpjolicoeur — APPROVED** [review]

**Pull request merged**
