### PR TITLE
Replace references to master with main

### PR DESCRIPTION
**Pull request by RocketPuppy**

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
@RocketPuppy Could you also update the places in the README file as well?

Also, is `main` the new git default, or do users need to opt-in still?  If its not the default, does the lab there `git init` is run need to have a flag added to use main or a local config option?

**Comment by RocketPuppy** [comment]
@cpjolicoeur Can change the README. Git 2.33.3 says master is still the default, as does https://git-scm.com/docs/git-init. So I'm actually not sure if this change is worth it anymore. It may only be the default on github.

**Comment by RocketPuppy** [comment]
I'm fine not changing to main if it's not the default. Are we in agreement @joealba @cpjolicoeur ?

**Comment by cpjolicoeur** [comment]
> I'm fine not changing to main if it's not the default. Are we in agreement @joealba @cpjolicoeur ?

Agreed.  I had the same customization in my gitconfig as @joealba, and if `master` is still the git default, I dont think we should change the exercise to use `main`

**Comment by joealba** [comment]
I vote for changing to `main` and recommending the config option for the same inclusivity reasons that github made it their default.  The effort is done now anyway.  :)

**Comment by RocketPuppy** [comment]
@cpjolicoeur Sounds good to me.

**Comment by joealba** [comment]
👍  I'm onboard, @cpjolicoeur.  It's essentially just another default to set on initial setup, like name/email -- but it's also a good one to set for important reasons.

**Comment by RocketPuppy** [comment]
@joealba @cpjolicoeur This has been updated and can be previewed at https://git.withmojo.com/dw/master-main/lab_01.html.

**Pull request merged**
